Repository OCA/account-fiscal-rule, pull requests merged in 2020-09, with the labels that each got.

#126 [IMP] account_avatax: on multicompany, Tax Exemption defined per Company
  account_avatax/models/account_move.py
  account_avatax/models/partner.py
  account_avatax/views/partner_view.xml
  account_avatax_sale/__manifest__.py
  account_avatax_sale/models/__init__.py
  account_avatax_sale/models/account_move.py
  account_avatax_sale/models/partner.py
  account_avatax_sale/models/sale_order.py
  account_avatax_sale/readme/USAGE.rst
  account_avatax_sale/views/partner_view.xml
Labels: bot is merging ⏳

#128 [13.0][FIX] account_avatax_sale: AttributeError: 'sale.order' object has no attribute 'tax_add_id'
  account_avatax_sale/models/sale_order.py
Labels: bot is merging ⏳, bug

#127 Fixes to pass Avalara Avatax certification
  account_avatax/models/account_move.py
  account_avatax/models/account_tax.py
  account_avatax/models/avatax_rest_api.py
Labels: bot is merging ⏳, bug

#125 [FIX] account_avatax: Ensure Avatax not called if no line has Avataxes
  account_avatax/models/account_move.py
  account_avatax_sale/models/sale_order.py
Labels: bot is merging ⏳, bug

#124 [FIX] account_avatax: v13 new syntax for company record rules
  account_avatax/security/avalara_salestax_security.xml
Labels: bot is merging ⏳, bug

#122 [FIX] account_avatax: Don't copy customer code and address validatin, when duplicating a Partner
  account_avatax/models/partner.py
Labels: bot is merging ⏳, bug

#130 [13.0][FIX] account_avatax: add result_in_uppercase option in Address validation
  account_avatax/models/avalara_salestax.py
  account_avatax/models/avatax_rest_api.py
  account_avatax/views/avalara_salestax_view.xml
Labels: bot is merging ⏳

#129 [FIX] account_avatax: Modified view name and XML ID
  account_avatax/views/avalara_salestax_view.xml
Labels: bot is merging ⏳

#123 [FIX] account_avatax: use for destination address the ship-to comped field, honoring the Tax on Shippling Address flag
  account_avatax/models/account_move.py
  account_avatax/views/account_move_view.xml
  account_avatax_sale/models/sale_order.py
Labels: bot is merging ⏳, bug

#131 [FIX] account_avatax: 100% discount lines should also be sent to Avatax
  account_avatax/models/avatax_rest_api.py
Labels: approved, bot is merging ⏳, bug

#132 [FIX] account_avatax: replace deprecated tax_exempt field in the Cust…
  account_avatax/views/partner_view.xml
Labels: approved, bot is merging ⏳, bug

#133 [FIX] account_avatax: ensure deprecated record rule is removed
  account_avatax/security/avalara_salestax_security.xml
Labels: approved, bot is merging ⏳, bug
