Repository OCA/account-fiscal-rule, pull requests merged in 2020-10, with the labels that each got.

#134 [FIX] account_avatax: fix record rule syntax, ensure it is applied on upgrade
  account_avatax/security/avalara_salestax_security.xml
Labels: bot is merging ⏳

#135 [FIX] account_avatax: Regular users can't set exemption status correctly (onchange does not work on readonly fields)
  account_avatax/models/account_move.py
  account_avatax_sale/models/account_move.py
  account_avatax_sale/models/sale_order.py
Labels: bot is merging ⏳, bug

#136 [IMP] account_avatax: usability, add Compute Taxes button to Sales Order and Invoice header buttons
  account_avatax/views/account_move_view.xml
  account_avatax_sale/views/sale_order_view.xml
Labels: bot is merging ⏳, enhancement

#137 [IMP] account_avatax: official Avalara certification awarded 🍾
  account_avatax/readme/DESCRIPTION.rst
Labels: bot is merging ⏳, enhancement

#107 [13.0] [MIG] Account Fiscal Position Rule Purchase
  account_fiscal_position_rule_purchase/README.rst
  account_fiscal_position_rule_purchase/__init__.py
  account_fiscal_position_rule_purchase/__manifest__.py
  account_fiscal_position_rule_purchase/i18n/account_fiscal_position_rule_purchase.pot
  account_fiscal_position_rule_purchase/i18n/es.po
  account_fiscal_position_rule_purchase/i18n/pt_BR.po
  account_fiscal_position_rule_purchase/i18n/sl.po
  account_fiscal_position_rule_purchase/models/__init__.py
  account_fiscal_position_rule_purchase/models/purchase.py
  account_fiscal_position_rule_purchase/readme/CONTRIBUTORS.rst
  account_fiscal_position_rule_purchase/readme/DESCRIPTION.rst
  account_fiscal_position_rule_purchase/static/description/index.html
  account_fiscal_position_rule_purchase/tests/__init__.py
  account_fiscal_position_rule_purchase/tests/test_account_fiscal_position_rule_purchase.py
  setup/account_fiscal_position_rule_purchase/.eggs/README.txt
  setup/account_fiscal_position_rule_purchase/odoo/addons/account_fiscal_position_rule_purchase
  setup/account_fiscal_position_rule_purchase/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#139 [FIX] account_avatax_sale: reapply exemptions when used fields are changed, such as Invoicing Address
  account_avatax_sale/models/sale_order.py
Labels: bot is merging ⏳, bug

#140 [FIX] allow to see products related to fiscal classification
  account_product_fiscal_classification/views/view_product_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#141 12.0 IMP prd_fisc_classif: track change on product model
  account_product_fiscal_classification/models/product_template.py
  account_product_fiscal_classification/readme/DESCRIPTION.rst
  account_product_fiscal_classification/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#142 [12.0][REF] account_avatax: remove Odoo SA from Authors, per Fabrice's request
  account_avatax/__manifest__.py
  account_avatax/readme/CREDITS.rst
  account_avatax/readme/DESCRIPTION.rst
  account_avatax_sale/__manifest__.py
Labels: bot is merging ⏳

#143 [FIX] account_fiscal_position_type : do not crash if domain is not set
  account_fiscal_position_type/models/account_invoice.py
Labels: approved, bot is merging ⏳

#144 [FIX] account_avatax_sale: Compute button visible on confirmed Sale Orders, unless Locked
  account_avatax_sale/views/sale_order_view.xml
Labels: bot is merging ⏳, bug

#145 [FIX] account_avatax_sale: Field 'is_add_validate' definition not available
  account_avatax_sale/models/account_move.py
Labels: bot is merging ⏳
