Repository OCA/account-fiscal-rule, pull requests merged in 2020-11, with the labels that each got.

#146 [FIX] account_avatax: Update taxes only for Draft Invoices
  account_avatax/models/account_move.py
Labels: bot is merging ⏳

#149 [FIX] account_avatax: Skip Avatax computation if no configuration is found
  account_avatax/models/account_move.py
Labels: approved, bot is merging ⏳, bug

#105 [13.0] [IMP] Account Fiscal Position Rule: use country groups
  account_fiscal_position_rule/models/account_fiscal_position_rule.py
  account_fiscal_position_rule/models/account_fiscal_position_rule_template.py
  account_fiscal_position_rule/views/account_fiscal_position_rule_template_view.xml
  account_fiscal_position_rule/views/account_fiscal_position_rule_view.xml
  account_fiscal_position_rule/wizard/wizard_account_fiscal_position_rule.py
  setup/account_fiscal_position_rule/.eggs/README.txt
Labels: approved, bot is merging ⏳
