Repository OCA/account-fiscal-rule, pull requests merged in 2021-07, with the labels that each got.

#210 11.0 mig account fiscal position partner type
  .travis.yml
  account_fiscal_position_partner_type/__init__.py
  account_fiscal_position_partner_type/__manifest__.py
  account_fiscal_position_partner_type/models/__init__.py
  account_fiscal_position_partner_type/models/account_fiscal_position.py
  account_fiscal_position_partner_type/models/res_company.py
  account_fiscal_position_partner_type/models/res_partner.py
  account_fiscal_position_partner_type/readme/CONFIGURE.rst
  account_fiscal_position_partner_type/readme/CONTRIBUTORS.rst
  account_fiscal_position_partner_type/readme/DESCRIPTION.rst
  account_fiscal_position_partner_type/readme/USAGE.rst
  account_fiscal_position_partner_type/static/description/icon.png
  account_fiscal_position_partner_type/tests/__init__.py
  account_fiscal_position_partner_type/tests/test_account_fiscal_position_partner_type.py
  account_fiscal_position_partner_type/views/account_fiscal_position.xml
  account_fiscal_position_partner_type/views/res_company.xml
  account_fiscal_position_partner_type/views/res_partner.xml
  setup/account_fiscal_position_partner_type/odoo/addons/account_fiscal_position_partner_type
  setup/account_fiscal_position_partner_type/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#214 [14.0][MIG] Account Fiscal Position Partner Type: Migrated into v14
  account_fiscal_position_partner_type/README.rst
  account_fiscal_position_partner_type/__init__.py
  account_fiscal_position_partner_type/__manifest__.py
  account_fiscal_position_partner_type/i18n/account_fiscal_position_partner_type.pot
  account_fiscal_position_partner_type/models/__init__.py
  account_fiscal_position_partner_type/models/account_fiscal_position.py
  account_fiscal_position_partner_type/models/res_company.py
  account_fiscal_position_partner_type/models/res_partner.py
  account_fiscal_position_partner_type/readme/CONFIGURE.rst
  account_fiscal_position_partner_type/readme/CONTRIBUTORS.rst
  account_fiscal_position_partner_type/readme/DESCRIPTION.rst
  account_fiscal_position_partner_type/readme/USAGE.rst
  account_fiscal_position_partner_type/static/description/icon.png
  account_fiscal_position_partner_type/static/description/index.html
  account_fiscal_position_partner_type/tests/__init__.py
  account_fiscal_position_partner_type/tests/test_account_fiscal_position_partner_type.py
  account_fiscal_position_partner_type/views/account_fiscal_position.xml
  account_fiscal_position_partner_type/views/res_company.xml
  account_fiscal_position_partner_type/views/res_partner.xml
  setup/account_fiscal_position_partner_type/odoo/addons/account_fiscal_position_partner_type
  setup/account_fiscal_position_partner_type/setup.py
Labels: bot is merging ⏳

#221 [14.0][MIG] l10n_eu_oss: Migration to 14.0
  l10n_eu_oss/README.rst
  l10n_eu_oss/__init__.py
  l10n_eu_oss/__manifest__.py
  l10n_eu_oss/data/oss.tax.rate.csv
  l10n_eu_oss/i18n/l10n_eu_oss.pot
  l10n_eu_oss/models/__init__.py
  l10n_eu_oss/models/account_tax.py
  l10n_eu_oss/models/oss_tax_rate.py
  l10n_eu_oss/readme/CONFIGURE.rst
  l10n_eu_oss/readme/CONTRIBUTORS.rst
  l10n_eu_oss/readme/DESCRIPTION.rst
  l10n_eu_oss/readme/ROADMAP.rst
  l10n_eu_oss/readme/USAGE.rst
  l10n_eu_oss/security/ir.model.access.csv
  l10n_eu_oss/static/description/icon.png
  l10n_eu_oss/static/description/index.html
  l10n_eu_oss/tests/__init__.py
  l10n_eu_oss/tests/test_l10n_eu_oss.py
  l10n_eu_oss/views/res_config_settings.xml
  l10n_eu_oss/wizard/__init__.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.xml
  setup/l10n_eu_oss/odoo/addons/l10n_eu_oss
  setup/l10n_eu_oss/setup.py
Labels: bot is merging ⏳

#211 11.0 mig l10n eu oss
  l10n_eu_oss/__init__.py
  l10n_eu_oss/__manifest__.py
  l10n_eu_oss/data/oss.tax.rate.csv
  l10n_eu_oss/models/__init__.py
  l10n_eu_oss/models/account_tax.py
  l10n_eu_oss/models/oss_tax_rate.py
  l10n_eu_oss/readme/CONFIGURE.rst
  l10n_eu_oss/readme/CONTRIBUTORS.rst
  l10n_eu_oss/readme/DESCRIPTION.rst
  l10n_eu_oss/readme/ROADMAP.rst
  l10n_eu_oss/readme/USAGE.rst
  l10n_eu_oss/security/ir.model.access.csv
  l10n_eu_oss/static/description/icon.png
  l10n_eu_oss/tests/__init__.py
  l10n_eu_oss/tests/test_l10n_eu_oss.py
  l10n_eu_oss/views/res_config_settings.xml
  l10n_eu_oss/wizard/__init__.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.xml
  setup/l10n_eu_oss/odoo/addons/l10n_eu_oss
  setup/l10n_eu_oss/setup.py
Labels: bot is merging ⏳

#215 [MIG] [12.0] mig account fiscal position partner type
  account_fiscal_position_partner_type/__init__.py
  account_fiscal_position_partner_type/__manifest__.py
  account_fiscal_position_partner_type/models/__init__.py
  account_fiscal_position_partner_type/models/account_fiscal_position.py
  account_fiscal_position_partner_type/models/res_company.py
  account_fiscal_position_partner_type/models/res_partner.py
  account_fiscal_position_partner_type/readme/CONFIGURE.rst
  account_fiscal_position_partner_type/readme/CONTRIBUTORS.rst
  account_fiscal_position_partner_type/readme/DESCRIPTION.rst
  account_fiscal_position_partner_type/readme/USAGE.rst
  account_fiscal_position_partner_type/static/description/icon.png
  account_fiscal_position_partner_type/tests/__init__.py
  account_fiscal_position_partner_type/tests/test_account_fiscal_position_partner_type.py
  account_fiscal_position_partner_type/views/account_fiscal_position.xml
  account_fiscal_position_partner_type/views/res_company.xml
  account_fiscal_position_partner_type/views/res_partner.xml
  setup/account_fiscal_position_partner_type/odoo/addons/account_fiscal_position_partner_type
  setup/account_fiscal_position_partner_type/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#223 [14.0][FIX + IMP] l10n_eu_oss removed UK taxes, fixed Slovenia taxes and some readme improvements
  l10n_eu_oss/data/oss.tax.rate.csv
  l10n_eu_oss/readme/DESCRIPTION.rst
  l10n_eu_oss/readme/ROADMAP.rst
Labels: approved, bot is merging ⏳

#227 [13.0] [IMP] Improved string in fiscal position type
  account_fiscal_position_partner_type/models/account_fiscal_position.py
Labels: approved, bot is merging ⏳

#228 [8.0][MIG] account_fiscal_position_partner_type: Backport to 8.0
  .travis.yml
  account_fiscal_position_partner_type/__init__.py
  account_fiscal_position_partner_type/__openerp__.py
  account_fiscal_position_partner_type/models/__init__.py
  account_fiscal_position_partner_type/models/account_fiscal_position.py
  account_fiscal_position_partner_type/models/res_company.py
  account_fiscal_position_partner_type/models/res_partner.py
  account_fiscal_position_partner_type/readme/CONFIGURE.rst
  account_fiscal_position_partner_type/readme/CONTRIBUTORS.rst
  account_fiscal_position_partner_type/readme/DESCRIPTION.rst
  account_fiscal_position_partner_type/readme/USAGE.rst
  account_fiscal_position_partner_type/static/description/icon.png
  account_fiscal_position_partner_type/tests/__init__.py
  account_fiscal_position_partner_type/tests/test_account_fiscal_position_partner_type.py
  account_fiscal_position_partner_type/views/account_fiscal_position.xml
  account_fiscal_position_partner_type/views/res_company.xml
  account_fiscal_position_partner_type/views/res_partner.xml
  setup/account_fiscal_position_partner_type/odoo/addons/account_fiscal_position_partner_type
  setup/account_fiscal_position_partner_type/setup.py
Labels: bot is merging ⏳

#225 [8.0] [MIG] l10n_eu_oss: Backport to 8.0
  l10n_eu_oss/__init__.py
  l10n_eu_oss/__openerp__.py
  l10n_eu_oss/data/oss.tax.rate.csv
  l10n_eu_oss/models/__init__.py
  l10n_eu_oss/models/account_tax.py
  l10n_eu_oss/models/oss_tax_rate.py
  l10n_eu_oss/readme/CONFIGURE.rst
  l10n_eu_oss/readme/CONTRIBUTORS.rst
  l10n_eu_oss/readme/DESCRIPTION.rst
  l10n_eu_oss/readme/ROADMAP.rst
  l10n_eu_oss/readme/USAGE.rst
  l10n_eu_oss/security/ir.model.access.csv
  l10n_eu_oss/static/description/icon.png
  l10n_eu_oss/tests/__init__.py
  l10n_eu_oss/tests/test_l10n_eu_oss.py
  l10n_eu_oss/views/res_config_settings.xml
  l10n_eu_oss/wizard/__init__.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.xml
  setup/l10n_eu_oss/odoo/addons/l10n_eu_oss
  setup/l10n_eu_oss/setup.py
Labels: bot is merging ⏳

#216 [12.0] [MIG] l10n eu oss
  l10n_eu_oss/__init__.py
  l10n_eu_oss/__manifest__.py
  l10n_eu_oss/data/oss.tax.rate.csv
  l10n_eu_oss/models/__init__.py
  l10n_eu_oss/models/account_tax.py
  l10n_eu_oss/models/oss_tax_rate.py
  l10n_eu_oss/readme/CONFIGURE.rst
  l10n_eu_oss/readme/CONTRIBUTORS.rst
  l10n_eu_oss/readme/DESCRIPTION.rst
  l10n_eu_oss/readme/ROADMAP.rst
  l10n_eu_oss/readme/USAGE.rst
  l10n_eu_oss/security/ir.model.access.csv
  l10n_eu_oss/static/description/icon.png
  l10n_eu_oss/tests/__init__.py
  l10n_eu_oss/tests/test_l10n_eu_oss.py
  l10n_eu_oss/views/res_config_settings.xml
  l10n_eu_oss/wizard/__init__.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.xml
  setup/l10n_eu_oss/odoo/addons/l10n_eu_oss
  setup/l10n_eu_oss/setup.py
Labels: approved, bot is merging ⏳
