Repository OCA/account-fiscal-rule, pull requests merged in 2021-05, with the labels that each got.

#190 [FIX] account_avatax, account_avatax_sale: Avatax calculation for Line with notes/section
  account_avatax/models/account_move.py
  account_avatax_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#191 [FIX] account_avatax: full refund, closes #171
  account_avatax/models/account_move.py
Labels: approved, bot is merging ⏳

#194 [FIX] account_avatax: full refund, closes
  account_avatax/models/account_move.py
Labels: bot is merging ⏳

#195 [14.0][IMP] account_avatax: is now Avalara certified!
  account_avatax/__manifest__.py
  account_avatax/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#196 [13.0][FIX] account_avatax: app store images
  account_avatax/__manifest__.py
Labels: bot is merging ⏳

#197 [FIX] action post method
  account_avatax/models/account_move.py
Labels: bot is merging ⏳

#198 [13.0][FIX] account_avatax: Res -> Self on Avatax
  account_avatax/models/account_move.py
Labels: bot is merging ⏳

#200 [14.0][FIX] account_avatax,account_avatax_sale: avoid long field computations on module install
  account_avatax/models/account_move.py
  account_avatax_sale/models/sale_order.py
Labels: bot is merging ⏳

#201 [13.0][FIX] account_avatax,account_avatax_sale: avoid long field computations on module install
  account_avatax/models/account_move.py
  account_avatax_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#199 [14.0][FIX] account_avatax: Fix tax computation for multi-company and tax exemption on some detail taxes
  account_avatax/models/account_move.py
  account_avatax/models/account_tax.py
  account_avatax/models/avatax_rest_api.py
  account_avatax/tests/__init__.py
  account_avatax/tests/test_account_tax.py
  account_avatax/tests/test_rest_api.py
  account_avatax_sale/models/sale_order.py
Labels: bot is merging ⏳, bug

#204 [FIX] account_avatax: Get username & password from config
  account_avatax/models/avatax_rest_api.py
Labels: bot is merging ⏳
