Repository OCA/account-fiscal-rule, pull requests merged in 2021-06, with the labels that each got.

#205 [ADD] account_avatax_website_sale: module to recalculate taxes prior to taking payment for website order
  account_avatax_website_sale/README.rst
  account_avatax_website_sale/__init__.py
  account_avatax_website_sale/__manifest__.py
  account_avatax_website_sale/controllers/__init__.py
  account_avatax_website_sale/controllers/main.py
  account_avatax_website_sale/readme/CONTRIBUTORS.rst
  account_avatax_website_sale/readme/DESCRIPTION.rst
  account_avatax_website_sale/readme/USAGE.rst
  setup/account_avatax_website_sale/odoo/addons/account_avatax_website_sale
  setup/account_avatax_website_sale/setup.py
Labels: bot is merging ⏳

#162 [14.0][ADD] account_avatax_exemption
  account_avatax_exemption/README.rst
  account_avatax_exemption/__init__.py
  account_avatax_exemption/__manifest__.py
  account_avatax_exemption/controller/__init__.py
  account_avatax_exemption/controller/main.py
  account_avatax_exemption/data/cron.xml
  account_avatax_exemption/data/ir_sequence_data.xml
  account_avatax_exemption/data/queue.xml
  account_avatax_exemption/models/__init__.py
  account_avatax_exemption/models/avalara_salestax.py
  account_avatax_exemption/models/exemption.py
  account_avatax_exemption/models/product.py
  account_avatax_exemption/models/queue_job.py
  account_avatax_exemption/models/res_country_state.py
  account_avatax_exemption/readme/CONTRIBUTORS.rst
  account_avatax_exemption/readme/DESCRIPTION.rst
  account_avatax_exemption/readme/USAGE.rst
  account_avatax_exemption/security/ir.model.access.csv
  account_avatax_exemption/static/description/icon.png
  account_avatax_exemption/static/description/index.html
  account_avatax_exemption/static/description/menu_icon.png
  account_avatax_exemption/views/avalara_exemption_view.xml
  account_avatax_exemption/views/avalara_salestax_view.xml
  account_avatax_exemption/views/exemption_template_views.xml
  account_avatax_exemption/views/product_view.xml
  account_avatax_exemption/views/res_country_state_view.xml
  account_avatax_exemption/views/website_exemption_form.xml
  account_avatax_exemption/views/website_exemption_tree.xml
  account_avatax_exemption/views/website_layout.xml
  account_avatax_exemption_base/README.rst
  account_avatax_exemption_base/__init__.py
  account_avatax_exemption_base/__manifest__.py
  account_avatax_exemption_base/data/ir_sequence_data.xml
  account_avatax_exemption_base/models/__init__.py
  account_avatax_exemption_base/models/exemption.py
  account_avatax_exemption_base/models/partner.py
  account_avatax_exemption_base/models/res_country_state.py
  account_avatax_exemption_base/readme/CONTRIBUTORS.rst
  account_avatax_exemption_base/readme/DESCRIPTION.rst
  account_avatax_exemption_base/readme/USAGE.rst
  account_avatax_exemption_base/security/ir.model.access.csv
  account_avatax_exemption_base/static/description/icon.png
  account_avatax_exemption_base/static/description/index.html
  account_avatax_exemption_base/static/description/menu_icon.png
  account_avatax_exemption_base/views/avalara_exemption_view.xml
  account_avatax_exemption_base/views/partner_view.xml
  account_avatax_exemption_base/views/res_country_state_view.xml
  setup/account_avatax_exemption/odoo/addons/account_avatax_exemption
  setup/account_avatax_exemption/setup.py
  setup/account_avatax_exemption_base/odoo/addons/account_avatax_exemption_base
  setup/account_avatax_exemption_base/setup.py
Labels: approved, bot is merging ⏳, needs review

#208 [FIX] account_avatax_exemption_base: license must be AGPL because of dependencies
  account_avatax_exemption_base/__manifest__.py
Labels: approved, bot is merging ⏳

#206 [13.0][ADD] Account Fiscal Position Partner Type
  account_fiscal_position_partner_type/__init__.py
  account_fiscal_position_partner_type/__manifest__.py
  account_fiscal_position_partner_type/models/__init__.py
  account_fiscal_position_partner_type/models/account_fiscal_position.py
  account_fiscal_position_partner_type/models/res_company.py
  account_fiscal_position_partner_type/models/res_partner.py
  account_fiscal_position_partner_type/readme/CONFIGURE.rst
  account_fiscal_position_partner_type/readme/CONTRIBUTORS.rst
  account_fiscal_position_partner_type/readme/DESCRIPTION.rst
  account_fiscal_position_partner_type/readme/USAGE.rst
  account_fiscal_position_partner_type/static/description/icon.png
  account_fiscal_position_partner_type/tests/__init__.py
  account_fiscal_position_partner_type/tests/test_account_fiscal_position_partner_type.py
  account_fiscal_position_partner_type/views/account_fiscal_position.xml
  account_fiscal_position_partner_type/views/res_company.xml
  account_fiscal_position_partner_type/views/res_partner.xml
  setup/account_fiscal_position_partner_type/odoo/addons/account_fiscal_position_partner_type
  setup/account_fiscal_position_partner_type/setup.py
Labels: approved, bot is merging ⏳

#207 [13.0][ADD]L10n EU OSS
  l10n_eu_oss/__init__.py
  l10n_eu_oss/__manifest__.py
  l10n_eu_oss/data/oss.tax.rate.csv
  l10n_eu_oss/models/__init__.py
  l10n_eu_oss/models/account_tax.py
  l10n_eu_oss/models/oss_tax_rate.py
  l10n_eu_oss/readme/CONFIGURE.rst
  l10n_eu_oss/readme/CONTRIBUTORS.rst
  l10n_eu_oss/readme/DESCRIPTION.rst
  l10n_eu_oss/readme/ROADMAP.rst
  l10n_eu_oss/readme/USAGE.rst
  l10n_eu_oss/security/ir.model.access.csv
  l10n_eu_oss/static/description/icon.png
  l10n_eu_oss/tests/__init__.py
  l10n_eu_oss/tests/test_l10n_eu_oss.py
  l10n_eu_oss/views/res_config_settings.xml
  l10n_eu_oss/wizard/__init__.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.xml
  setup/l10n_eu_oss/odoo/addons/l10n_eu_oss
  setup/l10n_eu_oss/setup.py
Labels: approved, bot is merging ⏳

#217 [13.0][IMP] l10n_eu_oss: tax groups are created and searched for the new taxes.
  l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
Labels: approved, bot is merging ⏳

#222 [FIX + IMP]l10n_eu_oss removed UK taxes, fixed Slovenia taxes and some readme improvements
  l10n_eu_oss/data/oss.tax.rate.csv
  l10n_eu_oss/readme/DESCRIPTION.rst
  l10n_eu_oss/readme/ROADMAP.rst
Labels: bot is merging ⏳
