Repository OCA/account-fiscal-rule, pull requests merged in 2022-08, with the labels that each got.

#232 [14.0] account_avatax_exemption_base: change license to LGPL
  account_avatax/models/partner.py
  account_avatax_exemption/__manifest__.py
  account_avatax_exemption/models/exemption.py
  account_avatax_exemption/security/ir.model.access.csv
  account_avatax_exemption/views/avalara_exemption_view.xml
  account_avatax_exemption/views/partner_view.xml
  account_avatax_exemption_base/__manifest__.py
  account_avatax_exemption_base/models/exemption.py
  account_avatax_exemption_base/models/partner.py
  account_avatax_exemption_base/security/ir.model.access.csv
  account_avatax_exemption_base/views/avalara_exemption_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#237 [14.0] account_avatax: Add Taxoverride for Credit notes(Refund)
  account_avatax/__manifest__.py
  account_avatax/models/account_move.py
  account_avatax/models/avalara_salestax.py
  account_avatax/models/avatax_rest_api.py
  account_avatax/security/avalara_salestax_security.xml
  account_avatax/views/account_move_view.xml
  account_avatax/wizard/__init__.py
  account_avatax/wizard/account_move_reversal.py
  account_avatax/wizard/account_move_reversal.xml
  account_avatax_exemption/models/avalara_salestax.py
Labels: bot is merging ⏳

#277 [15.0][FIX] Improved the account_avatax module code (FW #274)
  account_avatax/models/account_tax.py
Labels: bot is merging ⏳, stale

#284 [15.0][FIX] account_avatax: allow importing partner customer codes
  account_avatax/models/partner.py
  account_avatax/tests/__init__.py
  account_avatax/tests/test_account_tax.py
  account_avatax/tests/test_avatax.py
  account_avatax/tests/test_parter.py
  account_avatax/tests/test_rest_api.py
Labels: bot is merging ⏳

#285 [FIX][14.0] account_avatax
  account_avatax/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#307 [15.0][FIX] account_avatax: Field 'salespersonCode' has an invalid length (FW 290)
  account_avatax/models/avatax_rest_api.py
Labels: bot is merging ⏳

#308 [15.0][FIX] account_avatax: Validation Error adding Invoice Line/Section (FW 285)
  account_avatax/models/account_move.py
Labels: bot is merging ⏳

#309 [14.0][REF] pre-commit autoupdate
  .pre-commit-config.yaml
  account_product_fiscal_classification/hooks.py
Labels: bot is merging ⏳

#311 [15.0][IMP] account_avatax: Add Hide Exemption & Tax Based on shipping address option (FW 278)
  account_avatax/models/account_move.py
  account_avatax/models/avalara_salestax.py
  account_avatax/readme/CONFIGURE.rst
  account_avatax/readme/CONTRIBUTORS.rst
  account_avatax/views/account_move_view.xml
  account_avatax/views/avalara_salestax_view.xml
Labels: bot is merging ⏳

#278 [IMP][14.0][account_avatax] Add Hide Exemption & Tax Based on shipping address option
  account_avatax/models/account_move.py
  account_avatax/models/avalara_salestax.py
  account_avatax/readme/CONFIGURE.rst
  account_avatax/readme/CONTRIBUTORS.rst
  account_avatax/views/account_move_view.xml
  account_avatax/views/avalara_salestax_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#312 [15.0][IMP] account_avatax_sale: Add hide Exemption & Tax based on shipping address feature to sale (FW #279)
  account_avatax_sale/models/avalara_salestax.py
  account_avatax_sale/models/sale_order.py
  account_avatax_sale/readme/CONTRIBUTORS.rst
  account_avatax_sale/readme/USAGE.rst
  account_avatax_sale/views/sale_order_view.xml
Labels: bot is merging ⏳

#279 [IMP][14.0][account_avatax_sale]Add hide Exemption & Tax based on shipping address feature to sale
  account_avatax_sale/models/avalara_salestax.py
  account_avatax_sale/models/sale_order.py
  account_avatax_sale/readme/CONTRIBUTORS.rst
  account_avatax_sale/readme/USAGE.rst
  account_avatax_sale/views/sale_order_view.xml
Labels: approved, ready to merge, bot is merging ⏳
