Repository OCA/account-fiscal-rule, pull requests merged in 2023-08, with the labels that each got.

#336 [14.0][FIX] account_avatax_oca: don't overwrite date on refund
  account_avatax_oca/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳, no stale

#352 [FIX] account_avatax_oca: Don't override the invoice date when reversing moves
  account_avatax_oca/models/account_move.py
Labels: bot is merging ⏳, stale

#362 [IMP] account_avatax_oca: add search criteria to avoid singleton
  account_avatax_oca/models/account_move.py
Labels: bot is merging ⏳

#363 [16.0][MIG] account_avatax_website_sale
  account_avatax_website_sale/README.rst
  account_avatax_website_sale/__init__.py
  account_avatax_website_sale/__manifest__.py
  account_avatax_website_sale/controllers/__init__.py
  account_avatax_website_sale/controllers/main.py
  account_avatax_website_sale/i18n/account_avatax_website_sale.pot
  account_avatax_website_sale/readme/CONTRIBUTORS.rst
  account_avatax_website_sale/readme/DESCRIPTION.rst
  account_avatax_website_sale/readme/USAGE.rst
  account_avatax_website_sale/static/description/icon.png
  account_avatax_website_sale/static/description/index.html
  setup/account_avatax_website_sale/odoo/addons/account_avatax_website_sale
  setup/account_avatax_website_sale/setup.py
Labels: bot is merging ⏳
