Repository OCA/account-fiscal-rule, pull requests merged in 2023-12, with the labels that each got.

#396 [16.0][FIX] account_avatax_oca : use original parameters when calling super…
  account_avatax_oca/models/account_tax.py
Labels: bot is merging ⏳

#397 [16.0][FIX] account_avatax_oca : actually trigger avatax calculation on sav…
  account_avatax_oca/models/account_move.py
Labels: bot is merging ⏳

#398 [16.0][REM] account_avatax_oca : remove obsolete method "_get_price_total_a…
  account_avatax_oca/models/account_move.py
Labels: bot is merging ⏳

#400 FIX fisc_prd_class: set product_tax_multicompany_default as incompati…
  account_product_fiscal_classification/__manifest__.py
Labels: approved, bot is merging ⏳

#399 [16.0][FIX] l10n_eu_oss_oca: Set tax country_id as company's country
  l10n_eu_oss_oca/README.rst
  l10n_eu_oss_oca/__manifest__.py
  l10n_eu_oss_oca/migrations/16.0.1.0.1/post-migration.py
  l10n_eu_oss_oca/models/__init__.py
  l10n_eu_oss_oca/models/account_move.py
  l10n_eu_oss_oca/readme/CONTRIBUTORS.rst
  l10n_eu_oss_oca/static/description/index.html
  l10n_eu_oss_oca/tests/test_l10n_eu_oss.py
  l10n_eu_oss_oca/wizard/l10n_eu_oss_wizard.py
Labels: approved, ready to merge, bot is merging ⏳

#402 [16.0][FIX] l10n_eu_oss_oca: Set tax country_id as company's fiscal country
  l10n_eu_oss_oca/migrations/16.0.1.0.1/post-migration.py
  l10n_eu_oss_oca/tests/test_l10n_eu_oss.py
  l10n_eu_oss_oca/wizard/l10n_eu_oss_wizard.py
Labels: bot is merging ⏳

#403 [16.0][FWP] account_avatax_oca: don't overwrite date on refund
  account_avatax_oca/models/account_move.py
Labels: bot is merging ⏳

#373 [16.0][MIG] account_avatax_exemption_base: Migration to 16.0
  account_avatax_exemption_base/README.rst
  account_avatax_exemption_base/__init__.py
  account_avatax_exemption_base/__manifest__.py
  account_avatax_exemption_base/data/ir_sequence_data.xml
  account_avatax_exemption_base/i18n/account_avatax_exemption_base.pot
  account_avatax_exemption_base/models/__init__.py
  account_avatax_exemption_base/models/exemption.py
  account_avatax_exemption_base/models/partner.py
  account_avatax_exemption_base/models/res_country_state.py
  account_avatax_exemption_base/readme/CONTRIBUTORS.rst
  account_avatax_exemption_base/readme/DESCRIPTION.rst
  account_avatax_exemption_base/readme/USAGE.rst
  account_avatax_exemption_base/security/ir.model.access.csv
  account_avatax_exemption_base/static/description/icon.png
  account_avatax_exemption_base/static/description/index.html
  account_avatax_exemption_base/static/description/menu_icon.png
  account_avatax_exemption_base/views/avalara_exemption_view.xml
  account_avatax_exemption_base/views/res_country_state_view.xml
  setup/account_avatax_exemption_base/odoo/addons/account_avatax_exemption_base
  setup/account_avatax_exemption_base/setup.py
Labels: approved, bot is merging ⏳

#405 [16.0][IMP] account_avatax_oca: add search criteria to avoid singleton
  account_avatax_oca/models/account_move.py
Labels: bot is merging ⏳
