Repository OCA/account-fiscal-rule, pull requests merged in 2024-11, with the labels that each got.

#452 [FIX] account_fiscal_position_type: prevent error in demo / test mode, if l10n_generic_coa is not installed
  account_fiscal_position_type/__manifest__.py
  account_fiscal_position_type/demo/account_chart_template.xml
  account_fiscal_position_type/demo/account_fiscal_position_template.xml
  account_fiscal_position_type/tests/test_module.py
Labels: approved, bot is merging ⏳

#447 [14.0][FIX] l10n_eu_oss vat finland to 25.5
  l10n_eu_oss/data/oss.tax.rate.csv
Labels: bot is merging ⏳

#443 [16.0][IMP] account_avatax_oca|sale_oca : Add method to update tax details
  account_avatax_oca/models/account_move.py
  account_avatax_sale_oca/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳
