Repository OCA/account-fiscal-rule, pull requests merged in 2024-03, with the labels that each got.

#409 [14.0][FIX] l10n_eu_oss: Luxembourg VAT rate changed from 17% to 16%
  l10n_eu_oss/data/oss.tax.rate.csv
Labels: approved, bot is merging ⏳

#415 [17.0] [MIG] account_fiscal_position_partner_type
  account_fiscal_position_partner_type/README.rst
  account_fiscal_position_partner_type/__init__.py
  account_fiscal_position_partner_type/__manifest__.py
  account_fiscal_position_partner_type/i18n/account_fiscal_position_partner_type.pot
  account_fiscal_position_partner_type/i18n/es.po
  account_fiscal_position_partner_type/i18n/fr_FR.po
  account_fiscal_position_partner_type/i18n/it.po
  account_fiscal_position_partner_type/i18n/pt_PT.po
  account_fiscal_position_partner_type/models/__init__.py
  account_fiscal_position_partner_type/models/account_fiscal_position.py
  account_fiscal_position_partner_type/models/res_company.py
  account_fiscal_position_partner_type/models/res_partner.py
  account_fiscal_position_partner_type/pyproject.toml
  account_fiscal_position_partner_type/readme/CONFIGURE.md
  account_fiscal_position_partner_type/readme/CONTRIBUTORS.md
  account_fiscal_position_partner_type/readme/DESCRIPTION.md
  account_fiscal_position_partner_type/readme/USAGE.md
  account_fiscal_position_partner_type/static/description/icon.png
  account_fiscal_position_partner_type/static/description/index.html
  account_fiscal_position_partner_type/tests/__init__.py
  account_fiscal_position_partner_type/tests/test_account_fiscal_position_partner_type.py
  account_fiscal_position_partner_type/views/account_fiscal_position.xml
  account_fiscal_position_partner_type/views/res_company.xml
  account_fiscal_position_partner_type/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#416 [17.0] [MIG] l10n_eu_oss_oca
  l10n_eu_oss_oca/README.rst
  l10n_eu_oss_oca/__init__.py
  l10n_eu_oss_oca/__manifest__.py
  l10n_eu_oss_oca/data/oss.tax.rate.csv
  l10n_eu_oss_oca/i18n/es.po
  l10n_eu_oss_oca/i18n/fr_FR.po
  l10n_eu_oss_oca/i18n/it.po
  l10n_eu_oss_oca/i18n/l10n_eu_oss.pot
  l10n_eu_oss_oca/i18n/l10n_eu_oss_oca.pot
  l10n_eu_oss_oca/i18n/pt_PT.po
  l10n_eu_oss_oca/migrations/17.0.1.0.0/post-migration.py
  l10n_eu_oss_oca/models/__init__.py
  l10n_eu_oss_oca/models/account_fiscal_position.py
  l10n_eu_oss_oca/models/account_tax.py
  l10n_eu_oss_oca/models/oss_tax_rate.py
  l10n_eu_oss_oca/pyproject.toml
  l10n_eu_oss_oca/readme/CONFIGURE.md
  l10n_eu_oss_oca/readme/CONTRIBUTORS.md
  l10n_eu_oss_oca/readme/DESCRIPTION.md
  l10n_eu_oss_oca/readme/ROADMAP.md
  l10n_eu_oss_oca/readme/USAGE.md
  l10n_eu_oss_oca/security/ir.model.access.csv
  l10n_eu_oss_oca/static/description/icon.png
  l10n_eu_oss_oca/static/description/index.html
  l10n_eu_oss_oca/tests/__init__.py
  l10n_eu_oss_oca/tests/test_l10n_eu_oss.py
  l10n_eu_oss_oca/views/account_fiscal_position_views.xml
  l10n_eu_oss_oca/views/res_config_settings.xml
  l10n_eu_oss_oca/wizard/__init__.py
  l10n_eu_oss_oca/wizard/l10n_eu_oss_wizard.py
  l10n_eu_oss_oca/wizard/l10n_eu_oss_wizard.xml
Labels: approved, bot is merging ⏳

#413 [17.0] [MIG] account_avatax_sale_oca
  account_avatax_sale_oca/README.rst
  account_avatax_sale_oca/__init__.py
  account_avatax_sale_oca/__manifest__.py
  account_avatax_sale_oca/i18n/account_avatax_sale.pot
  account_avatax_sale_oca/i18n/account_avatax_sale_oca.pot
  account_avatax_sale_oca/i18n/it.po
  account_avatax_sale_oca/models/__init__.py
  account_avatax_sale_oca/models/account_move.py
  account_avatax_sale_oca/models/account_tax.py
  account_avatax_sale_oca/models/avalara_salestax.py
  account_avatax_sale_oca/models/sale_order.py
  account_avatax_sale_oca/pyproject.toml
  account_avatax_sale_oca/readme/CONTRIBUTORS.md
  account_avatax_sale_oca/readme/DESCRIPTION.md
  account_avatax_sale_oca/readme/USAGE.md
  account_avatax_sale_oca/static/description/icon.png
  account_avatax_sale_oca/static/description/index.html
  account_avatax_sale_oca/views/avalara_salestax_view.xml
  account_avatax_sale_oca/views/sale_order_view.xml
Labels: bot is merging ⏳

#407 [16.0][FIX] account_avatax_oca: changed colspan
  account_avatax_oca/views/product_view.xml
Labels: approved, bot is merging ⏳

#414 [17.0] [MIG] account_avatax_website_sale
  account_avatax_website_sale/README.rst
  account_avatax_website_sale/__init__.py
  account_avatax_website_sale/__manifest__.py
  account_avatax_website_sale/controllers/__init__.py
  account_avatax_website_sale/controllers/main.py
  account_avatax_website_sale/i18n/account_avatax_website_sale.pot
  account_avatax_website_sale/i18n/it.po
  account_avatax_website_sale/pyproject.toml
  account_avatax_website_sale/readme/CONTRIBUTORS.md
  account_avatax_website_sale/readme/DESCRIPTION.md
  account_avatax_website_sale/readme/USAGE.md
  account_avatax_website_sale/static/description/icon.png
  account_avatax_website_sale/static/description/index.html
Labels: bot is merging ⏳

#421 [17.0][FIX] account_avatax_oca: changed colspan to field
  account_avatax_oca/views/product_view.xml
Labels: bot is merging ⏳
