Repository OCA/account-fiscal-rule, pull requests merged in 2025-04, with the labels that each got.

#463 [15.0][MIG][BCK] account_avatax_exemption_base: backport from v16
  account_avatax_exemption_base/README.rst
  account_avatax_exemption_base/__init__.py
  account_avatax_exemption_base/__manifest__.py
  account_avatax_exemption_base/data/ir_sequence_data.xml
  account_avatax_exemption_base/i18n/account_avatax_exemption_base.pot
  account_avatax_exemption_base/i18n/it.po
  account_avatax_exemption_base/models/__init__.py
  account_avatax_exemption_base/models/exemption.py
  account_avatax_exemption_base/models/partner.py
  account_avatax_exemption_base/models/res_country_state.py
  account_avatax_exemption_base/readme/CONTRIBUTORS.rst
  account_avatax_exemption_base/readme/DESCRIPTION.rst
  account_avatax_exemption_base/readme/USAGE.rst
  account_avatax_exemption_base/security/ir.model.access.csv
  account_avatax_exemption_base/static/description/icon.png
  account_avatax_exemption_base/static/description/index.html
  account_avatax_exemption_base/static/description/menu_icon.png
  account_avatax_exemption_base/tests/__init__.py
  account_avatax_exemption_base/tests/test_account_avatax_exemtion_base.py
  account_avatax_exemption_base/views/avalara_exemption_view.xml
  account_avatax_exemption_base/views/res_country_state_view.xml
  setup/account_avatax_exemption_base/odoo/addons/account_avatax_exemption_base
  setup/account_avatax_exemption_base/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#520 [16.0][IMP] l10n_eu_oss_oca: Czech Republic, Estonia, Finland VAT
  l10n_eu_oss_oca/data/oss.tax.rate.csv
Labels: approved, merged 🎉

#517 [17.0][FIX] account_fiscal_position_partner_type: make fiscal_position_type field visible
  account_fiscal_position_partner_type/README.rst
  account_fiscal_position_partner_type/readme/CONTRIBUTORS.md
  account_fiscal_position_partner_type/static/description/index.html
  account_fiscal_position_partner_type/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#525 [16.0][FIX] account_fiscal_position_partner_type: Post-install test + fallback to load CoA
  account_fiscal_position_partner_type/tests/test_account_fiscal_position_partner_type.py
Labels: bot is merging ⏳
