Repository OCA/account-fiscal-rule, pull requests merged in 2025-03, with the labels that each got.

#480 [17.0][MIG] account_ecotax: Migration to 17.0
  account_ecotax/README.rst
  account_ecotax/__init__.py
  account_ecotax/__manifest__.py
  account_ecotax/data/decimal_precision.xml
  account_ecotax/models/__init__.py
  account_ecotax/models/account_ecotax_category.py
  account_ecotax/models/account_ecotax_classification.py
  account_ecotax/models/account_move.py
  account_ecotax/models/account_move_line.py
  account_ecotax/models/account_move_line_ecotax.py
  account_ecotax/models/ecotax_collector.py
  account_ecotax/models/ecotax_line_mixin.py
  account_ecotax/models/ecotax_line_product.py
  account_ecotax/models/ecotax_sector.py
  account_ecotax/models/product_product.py
  account_ecotax/models/product_template.py
  account_ecotax/pyproject.toml
  account_ecotax/readme/CONTRIBUTORS.md
  account_ecotax/readme/DESCRIPTION.md
  account_ecotax/readme/USAGE.md
  account_ecotax/report/invoice.xml
  account_ecotax/security/ir.model.access.csv
  account_ecotax/security/ir_rule.xml
  account_ecotax/static/description/icon.png
  account_ecotax/static/description/index.html
  account_ecotax/tests/__init__.py
  account_ecotax/tests/test_ecotax.py
  account_ecotax/views/account_ecotax_category_view.xml
  account_ecotax/views/account_ecotax_classification_view.xml
  account_ecotax/views/account_move_view.xml
  account_ecotax/views/ecotax_collector_view.xml
  account_ecotax/views/ecotax_sector_view.xml
  account_ecotax/views/product_template_view.xml
  account_ecotax/views/product_view.xml
Labels: approved, ready to merge

#488 [FIX] account_avatax_oca: return correct message format
  account_avatax_oca/models/partner.py
Labels: approved, bot is merging ⏳

#455 [16][REF] split account_ecotax_sale in account_ecotax_sale and account_ecotax_sale_tax
  account_avatax_sale_oca/views/sale_order_view.xml
  account_ecotax_sale/README.rst
  account_ecotax_sale/__init__.py
  account_ecotax_sale/__manifest__.py
  account_ecotax_sale/i18n/account_ecotaxe_sale.pot
  account_ecotax_sale/i18n/fr.po
  account_ecotax_sale/models/__init__.py
  account_ecotax_sale/models/sale_order.py
  account_ecotax_sale/models/sale_order_line.py
  account_ecotax_sale/models/sale_order_line_ecotax.py
  account_ecotax_sale/readme/CONTRIBUTORS.rst
  account_ecotax_sale/readme/DESCRIPTION.rst
  account_ecotax_sale/security/ir.model.access.csv
  account_ecotax_sale/static/description/icon.png
  account_ecotax_sale/static/description/index.html
  account_ecotax_sale/tests/__init__.py
  account_ecotax_sale/tests/test_sale_ecotax.py
  account_ecotax_sale/views/sale_view.xml
  account_ecotax_sale_tax/README.rst
  account_ecotax_sale_tax/__init__.py
  account_ecotax_sale_tax/__manifest__.py
  account_ecotax_sale_tax/models/__init__.py
  account_ecotax_sale_tax/models/sale_order_line.py
  account_ecotax_sale_tax/readme/CONTRIBUTORS.rst
  account_ecotax_sale_tax/readme/DESCRIPTION.rst
  account_ecotax_sale_tax/static/description/icon.png
  account_ecotax_sale_tax/static/description/index.html
  account_ecotax_sale_tax/tests/__init__.py
  account_ecotax_sale_tax/tests/test_sale_ecotax.py
  account_ecotax_sale_tax/views/sale_view.xml
  setup/account_ecotax_sale/odoo/addons/account_ecotax_sale
  setup/account_ecotax_sale/setup.py
  setup/account_ecotax_sale_tax/odoo/addons/account_ecotax_sale_tax
  setup/account_ecotax_sale_tax/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#446 [16.0][FIX] account_avatax_oca, force compute hearder taxes after onchange triggered
  account_avatax_oca/models/account_move.py
  account_avatax_oca/tests/mock_avatax.py
  account_avatax_oca/tests/test_avatax.py
Labels: bot is merging ⏳, stale

#489 [17.0][IMP] l10n_eu_oss_oca: Czech Republic, Estonia, Finland VAT
  l10n_eu_oss_oca/data/oss.tax.rate.csv
Labels: approved, bot is merging ⏳

#376 [16.0][ADD] account_avatax_oca_log
  account_avatax_oca/models/avatax_rest_api.py
  account_avatax_oca_log/README.rst
  account_avatax_oca_log/__init__.py
  account_avatax_oca_log/__manifest__.py
  account_avatax_oca_log/data/cron.xml
  account_avatax_oca_log/data/emails.xml
  account_avatax_oca_log/models/__init__.py
  account_avatax_oca_log/models/avalara_salestax.py
  account_avatax_oca_log/models/avatax_log.py
  account_avatax_oca_log/models/avatax_rest_api.py
  account_avatax_oca_log/models/res_config_settings.py
  account_avatax_oca_log/readme/CONTRIBUTORS.rst
  account_avatax_oca_log/readme/DESCRIPTION.rst
  account_avatax_oca_log/readme/USAGE.rst
  account_avatax_oca_log/security/ir.model.access.csv
  account_avatax_oca_log/static/description/icon.png
  account_avatax_oca_log/static/description/index.html
  account_avatax_oca_log/views/avatax_log_views.xml
  account_avatax_oca_log/views/res_config_settings_views.xml
  setup/account_avatax_oca_log/odoo/addons/account_avatax_oca_log
  setup/account_avatax_oca_log/setup.py
Labels: bot is merging ⏳, stale

#469 [16.0][FIX] account_avatax_oca: skip exception raise on lines with not product in display_type
  account_avatax_oca/README.rst
  account_avatax_oca/__init__.py
  account_avatax_oca/__manifest__.py
  account_avatax_oca/hooks.py
  account_avatax_oca/models/account_tax.py
  account_avatax_oca/readme/CONTRIBUTORS.rst
  account_avatax_oca/static/description/index.html
  account_avatax_oca/tests/test_account_tax.py
Labels: approved, bot is merging ⏳

#481 [17.0][MIG] account_ecotax_sale: Migration to 17.0
  account_avatax_sale_oca/views/sale_order_view.xml
  account_ecotax_sale/README.rst
  account_ecotax_sale/__init__.py
  account_ecotax_sale/__manifest__.py
  account_ecotax_sale/i18n/account_ecotaxe_sale.pot
  account_ecotax_sale/i18n/fr.po
  account_ecotax_sale/models/__init__.py
  account_ecotax_sale/models/sale_order.py
  account_ecotax_sale/models/sale_order_line.py
  account_ecotax_sale/models/sale_order_line_ecotax.py
  account_ecotax_sale/pyproject.toml
  account_ecotax_sale/readme/CONTRIBUTORS.md
  account_ecotax_sale/readme/DESCRIPTION.md
  account_ecotax_sale/security/ir.model.access.csv
  account_ecotax_sale/static/description/icon.png
  account_ecotax_sale/static/description/index.html
  account_ecotax_sale/tests/__init__.py
  account_ecotax_sale/tests/test_sale_ecotax.py
  account_ecotax_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#494 [18.0][FIX] account_avatax_oca, force compute hearder taxes after onchange triggered
  account_avatax_oca/models/account_move.py
  account_avatax_oca/tests/mock_avatax.py
  account_avatax_oca/tests/test_avatax.py
Labels: bot is merging ⏳

#493 [17.0][FIX] account_avatax_oca, force compute hearder taxes after onchange triggered
  account_avatax_oca/models/account_move.py
  account_avatax_oca/tests/mock_avatax.py
  account_avatax_oca/tests/test_avatax.py
Labels: bot is merging ⏳

#484 [IMP] account_avatax_exemption_base: remove chatter from wizard view
  account_avatax_exemption_base/views/avalara_exemption_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#476 [18.0][MIG] account_fiscal_position_partner_type
  account_fiscal_position_partner_type/README.rst
  account_fiscal_position_partner_type/__init__.py
  account_fiscal_position_partner_type/__manifest__.py
  account_fiscal_position_partner_type/i18n/account_fiscal_position_partner_type.pot
  account_fiscal_position_partner_type/i18n/es.po
  account_fiscal_position_partner_type/i18n/fr_FR.po
  account_fiscal_position_partner_type/i18n/it.po
  account_fiscal_position_partner_type/i18n/pt_PT.po
  account_fiscal_position_partner_type/models/__init__.py
  account_fiscal_position_partner_type/models/account_fiscal_position.py
  account_fiscal_position_partner_type/models/res_company.py
  account_fiscal_position_partner_type/models/res_partner.py
  account_fiscal_position_partner_type/pyproject.toml
  account_fiscal_position_partner_type/readme/CONFIGURE.md
  account_fiscal_position_partner_type/readme/CONTRIBUTORS.md
  account_fiscal_position_partner_type/readme/DESCRIPTION.md
  account_fiscal_position_partner_type/readme/USAGE.md
  account_fiscal_position_partner_type/static/description/icon.png
  account_fiscal_position_partner_type/static/description/index.html
  account_fiscal_position_partner_type/tests/__init__.py
  account_fiscal_position_partner_type/tests/test_account_fiscal_position_partner_type.py
  account_fiscal_position_partner_type/views/account_fiscal_position.xml
  account_fiscal_position_partner_type/views/res_company.xml
  account_fiscal_position_partner_type/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#460 [18.0][MIG] account_avatax_oca_log: Migration to 18.0
  account_avatax_oca_log/README.rst
  account_avatax_oca_log/__init__.py
  account_avatax_oca_log/__manifest__.py
  account_avatax_oca_log/data/cron.xml
  account_avatax_oca_log/data/emails.xml
  account_avatax_oca_log/models/__init__.py
  account_avatax_oca_log/models/avalara_salestax.py
  account_avatax_oca_log/models/avatax_log.py
  account_avatax_oca_log/models/avatax_rest_api.py
  account_avatax_oca_log/models/res_config_settings.py
  account_avatax_oca_log/pyproject.toml
  account_avatax_oca_log/readme/CONTRIBUTORS.md
  account_avatax_oca_log/readme/DESCRIPTION.md
  account_avatax_oca_log/readme/USAGE.md
  account_avatax_oca_log/security/ir.model.access.csv
  account_avatax_oca_log/static/description/icon.png
  account_avatax_oca_log/static/description/index.html
  account_avatax_oca_log/views/avatax_log_views.xml
  account_avatax_oca_log/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#457 [16.0][FIX] account_fiscal_position_type: use company from move
  account_fiscal_position_type/models/account_move.py
Labels: help wanted, needs review, bot is merging ⏳

#475 [18.0][MIG] account_avatax_exemption: Migration to 18.0
  account_avatax_exemption/README.rst
  account_avatax_exemption/__init__.py
  account_avatax_exemption/__manifest__.py
  account_avatax_exemption/controller/__init__.py
  account_avatax_exemption/controller/main.py
  account_avatax_exemption/data/cron.xml
  account_avatax_exemption/data/ir_sequence_data.xml
  account_avatax_exemption/data/queue.xml
  account_avatax_exemption/data/res_partner_exemption_business_type.xml
  account_avatax_exemption/i18n/account_avatax_exemption.pot
  account_avatax_exemption/models/__init__.py
  account_avatax_exemption/models/avalara_salestax.py
  account_avatax_exemption/models/exemption.py
  account_avatax_exemption/models/product.py
  account_avatax_exemption/models/queue_job.py
  account_avatax_exemption/models/res_country_state.py
  account_avatax_exemption/pyproject.toml
  account_avatax_exemption/readme/CONTRIBUTORS.md
  account_avatax_exemption/readme/DESCRIPTION.md
  account_avatax_exemption/readme/USAGE.md
  account_avatax_exemption/security/ir.model.access.csv
  account_avatax_exemption/static/description/avatax_icon.png
  account_avatax_exemption/static/description/icon.png
  account_avatax_exemption/static/description/index.html
  account_avatax_exemption/views/avalara_exemption_view.xml
  account_avatax_exemption/views/avalara_salestax_view.xml
  account_avatax_exemption/views/exemption_template_views.xml
  account_avatax_exemption/views/partner_view.xml
  account_avatax_exemption/views/product_view.xml
  account_avatax_exemption/views/res_country_state_view.xml
  account_avatax_exemption/views/website_exemption_form.xml
  account_avatax_exemption/views/website_exemption_tree.xml
  account_avatax_exemption/views/website_layout.xml
Labels: approved, bot is merging ⏳

#495 [16][account_ecotax] Store fields needed for reporting
  account_ecotax/__manifest__.py
  account_ecotax/migrations/16.0.1.1.0/post-migration.py
  account_ecotax/models/account_move_line_ecotax.py
Labels: approved, bot is merging ⏳

#508 [16] account_ecotax and account_ecotax_sale init computed fields on installation
  account_ecotax/__init__.py
  account_ecotax/__manifest__.py
  account_ecotax/hook.py
  account_ecotax_sale/__init__.py
  account_ecotax_sale/__manifest__.py
  account_ecotax_sale/hook.py
Labels: approved, ready to merge, bot is merging ⏳

#507 [15.0][IMP] update to copier v.129
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#467 [18.0][MIG] : account_avatax_website_sale Migration to 18.0
  account_avatax_website_sale/README.rst
  account_avatax_website_sale/__init__.py
  account_avatax_website_sale/__manifest__.py
  account_avatax_website_sale/controllers/__init__.py
  account_avatax_website_sale/controllers/main.py
  account_avatax_website_sale/i18n/account_avatax_website_sale.pot
  account_avatax_website_sale/i18n/it.po
  account_avatax_website_sale/pyproject.toml
  account_avatax_website_sale/readme/CONTRIBUTORS.md
  account_avatax_website_sale/readme/DESCRIPTION.md
  account_avatax_website_sale/readme/USAGE.md
  account_avatax_website_sale/static/description/icon.png
  account_avatax_website_sale/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#502 [17][IMP] Store all fields in account move line ecotax model
  account_ecotax/__manifest__.py
  account_ecotax/migrations/17.0.1.1.0/post-migration.py
  account_ecotax/models/account_move_line_ecotax.py
Labels: bot is merging ⏳
