Repository OCA/account-fiscal-rule, pull requests merged in 2025-07, with the labels that each got.

#499 [17.0][IMP] account_avatax_oca: add neutralization script
  account_avatax_oca/data/neutralize.sql
Labels: needs review, bot is merging ⏳, stale

#500 [18.0][IMP] account_avatax_oca: add neutralization script
  account_avatax_oca/data/neutralize.sql
Labels: bot is merging ⏳, stale

#541 [18.0][FIX] account_fiscal_position_partner_type: fiscal_position_type field position
  account_fiscal_position_partner_type/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳
